CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE bookmarks (
    id integer primary key generated by default as identity,
    title text not null,
    body text not null,
    weburl VARCHAR(2083) not null,
    rating star_rating not null
);